service: node-graphql

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  environment: ${file(env.yml):${self:provider.stage}}

functions:
  graphql:
    handler: src/server.graphqlHandler
    environment:
      SLS_DEBUG: true
    events:
    - http:
        path: graphql
        method: post
        cors: true
        integration: lambda-proxy
    - http:
        path: graphql
        method: get
        cors: true
        integration: lambda-proxy

plugins:
  - serverless-webpack
  - serverless-offline
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'npm'
    packagerOptions:
      scripts: # this is the magic
        - prisma generate 
  serverless-offline:
    httpPort: 3001
  apigwBinary:
    types:
      - 'multipart/form-data'

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
