name: Deploy Heroku

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/heroku@master
    - name: Deploy
      env: 
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/express-graphql.git origin/master:master  
